# Generated by Django 3.2 on 2023-02-11 07:05

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230211_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[api.validators.title_year_validator], verbose_name='Год публикации'),
        ),
    ]
