# Generated by Django 3.2 on 2023-02-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-id',)},
        ),
    ]
