# Generated by Django 3.2 on 2023-02-11 07:06

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[api.validators.title_year_validator], verbose_name='Год публикации'),
        ),
    ]
