# Generated by Django 3.2 on 2023-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230206_2133'),
        ('reviews', '0005_auto_20230206_0257'),
    ]

    operations = [
    ]
